services:
  - type: web
    name: flask-csv-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: neondb
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0